# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment # 만들려는 오브젝트 종류: 디플로이먼트
metadata:
  name: nginx-deployment # 이 디플로이먼트의 이름
spec:
  replicas: 1 # 몇 개의 파드를 실행할지: 1개
  selector:
    matchLabels:
      app: nginx # 이 디플로이먼트가 관리할 파드를 찾는 방법 (app=nginx 라벨)
  template: # 여기서부터는 생성될 파드의 설계도
    metadata:
      labels:
        app: nginx # 생성될 파드에 붙일 라벨 (위 selector와 일치해야 함)
    spec:
      containers: # 파드 안에서 실행될 컨테이너 목록
      - name: nginx # 컨테이너 이름
        image: nginx:latest # 사용할 도커 이미지 (이전과 동일)
        ports:
        - containerPort: 80 # 컨테이너가 내부적으로 사용할 포트